dist: trusty
sudo: required
services:
- docker
language: generic
before_install:
- docker pull ubuntu:16.04
- docker run ubuntu:16.04 /bin/sh -c "apt-get -qq update; apt-get install -y ubuntu-defaults-builder; ubuntu-defaults-image --locale nl_nl --components main,restricted,universe,multiverse; ls -al"
install:
- echo "Nothing to install"
script:
    - date
after_script:
- ls -al
